version: '3.8'

services:
 mongodb:
  image: mongo:7
  container_name: yttotext-mongodb
  restart: unless-stopped
  ports:
   - '${MONGO_PORT:-27017}:27017'
  environment:
   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
   MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-yttotext}
  volumes:
   - mongodb_data:/data/db
   - mongodb_config:/data/configdb
  networks:
   - yttotext-network

 server:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: yttotext-server
  restart: unless-stopped
  ports:
   - '${SERVER_PORT:-5000}:${PORT:-5000}'
  environment:
   NODE_ENV: ${NODE_ENV:-production}
   PORT: ${PORT:-5000}
   MONGODB_URI: ${MONGODB_URI}
   JWT_SECRET: ${JWT_SECRET}
   JWT_EXPIRE: ${JWT_EXPIRE:-7d}
   CLIENT_URL: ${CLIENT_URL}
   YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
   OPENAI_API_KEY: ${OPENAI_API_KEY}
   ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
   GEMINI_API_KEY: ${GEMINI_API_KEY}
   RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
   RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
   TRANSCRIPT_SERVICE: ${TRANSCRIPT_SERVICE:-auto}
   USE_PROXY: ${USE_PROXY:-false}
   PROXY_URL: ${PROXY_URL:-}
   ENABLE_MOCK_DATA: ${ENABLE_MOCK_DATA:-false}
   LOG_LEVEL: ${LOG_LEVEL:-info}
   APP_NAME: ${APP_NAME:-YTtoText}
   APP_URL: ${APP_URL}
  depends_on:
   - mongodb
  networks:
   - yttotext-network
  volumes:
   - ./server:/app/server:ro
   - /app/server/node_modules

 client:
  build:
   context: ./client
   dockerfile: Dockerfile.dev
  container_name: yttotext-client
  restart: unless-stopped
  ports:
   - '${CLIENT_PORT:-3000}:3000'
  environment:
   VITE_API_URL: ${VITE_API_URL}
  volumes:
   - ./client:/app:ro
   - /app/node_modules
  networks:
   - yttotext-network

volumes:
 mongodb_data:
 mongodb_config:

networks:
 yttotext-network:
  driver: bridge
